%% CONES_DEMO_ALL.M
% Visual summary of basic cone concepts for numerical optimization.
%
% Why are cones important in optimization?
% ----------------------------------------
% In constrained optimization we often care about "directions" in which
% we can move from a point x without violating constraints.
%
%   - Feasible direction cone: directions that keep us inside the
%     constraint set (locally).
%   - Tangent cone: limit of feasible directions near a point.
%   - Normal cone: directions that are "orthogonal" / blocking movement.
%   - KKT conditions: basically say that -grad f(x*) lies in the normal
%     cone of the feasible set at x*. This is a cone statement.
%
% In algorithms (projected gradient, SQP, interior-point) we do NOT
% usually "program" cones directly, but the theory of cones tells us
% which directions are allowed and how optimality conditions look.
%
% This script just builds geometric intuition.

clear; close all; clc;

% Prepare one figure with 2x2 subplots
figure(1);
tiledlayout(2,2,'Padding','compact','TileSpacing','compact');


%% (a) S1 and the cone generated by S1
% S1 is the line segment between A = (-1,1) and B = (1,1).
% The cone K is the union of all rays from the origin passing through S1.
% This is a "wedge" of feasible directions.

A = [-1; 1];
B = [ 1; 1];

beta  = linspace(0,1,200);
S1    = beta .* A + (1-beta) .* B;   % points on the segment S1

nexttile;  % subplot (1,1)
hold on; grid on; axis equal;
xlabel('x_1'); ylabel('x_2');
title('(a) Segment S_1 and its cone K');

% draw S1 (blue segment)
plot(S1(1,:), S1(2,:), 'b', 'LineWidth', 2);

% draw cone K: for each point x in S1, draw the ray { alpha x | alpha >= 0 }
alphas = linspace(0,2.5,40);

for k = 1:length(beta)
    x   = S1(:,k);
    ray = alphas .* x;
    plot(ray(1,:), ray(2,:), 'c');
end

plot(0,0,'ko','MarkerFaceColor','k');  % origin

legend('Segment S_1','Rays \alpha x, \alpha \ge 0','Origin','Location','northwest');

% small text explanation inside the plot
text(0.1,2.1,'Cone = all nonnegative','FontSize',8);
text(0.1,1.9,'scalings of S_1','FontSize',8);


%% (b) S2 such that its cone is all of R^2
% We take S2 = { x : ||x|| = 1 }, the unit circle.
% Any nonzero vector v can be written as v = ||v|| * (v / ||v||),
% where (v / ||v||) is on the unit circle. So the cone is ALL of R^2.

theta     = linspace(0, 2*pi, 400);
circle_x  = cos(theta);
circle_y  = sin(theta);

nexttile;  % subplot (1,2)
hold on; grid on; axis equal;
xlabel('x_1'); ylabel('x_2');
title('(b) S_2 = unit circle, cone(S_2) = R^2');

% plot S2 (unit circle)
plot(circle_x, circle_y, 'b', 'LineWidth', 2);

% plot some rays to suggest that the cone covers all directions
directions = linspace(0, 2*pi, 16);
alphas     = linspace(0, 2, 50);

for k = 1:length(directions)
    dir = [cos(directions(k)); sin(directions(k))]; % unit direction
    ray = alphas .* dir;
    plot(ray(1,:), ray(2,:), 'r');
end

plot(0,0,'ko','MarkerFaceColor','k');

legend('S_2 (unit circle)','Some rays of the cone','Origin','Location','best');

% in-plot explanation
text(-1.9,1.8,'Any nonzero v = ||v|| * u,','FontSize',8);
text(-1.9,1.6,'with u on the unit circle.','FontSize',8);
text(-1.9,1.4,'=> cone(S_2) = R^2','FontSize',8);


%% (c) Example of a NON-CONVEX cone
% K = { alpha e1 | alpha >= 0 } U { alpha e2 | alpha >= 0 },
% where e1 = (1,0), e2 = (0,1).
% This is a cone (closed under positive scaling) but NOT convex:
% the midpoint between e1 and e2 is not in K.

e1 = [1; 0];
e2 = [0; 1];

t  = linspace(0, 2, 100);

nexttile;  % subplot (2,1)
hold on; grid on; axis equal;
xlabel('x_1'); ylabel('x_2');
title('(c) Non-convex cone: positive x-axis U positive y-axis');

% positive x-axis
plot(t, 0*t, 'b', 'LineWidth', 2);
% positive y-axis
plot(0*t, t, 'b', 'LineWidth', 2);

% mark e1 and e2
plot(e1(1), e1(2), 'ro', 'MarkerSize', 8, 'MarkerFaceColor','r');
plot(e2(1), e2(2), 'ro', 'MarkerSize', 8, 'MarkerFaceColor','r');
text(e1(1)+0.05, e1(2), 'e_1','FontSize',8);
text(e2(1), e2(2)+0.05, 'e_2','FontSize',8);

% midpoint
m = 0.5*e1 + 0.5*e2;
plot(m(1), m(2), 'ks', 'MarkerSize', 8, 'MarkerFaceColor','y');
text(m(1)+0.05, m(2)+0.05, 'midpoint','FontSize',8);

legend('Positive x-axis','Positive y-axis','e_1','e_2','midpoint (not in K)',...
       'Location','northeast');

% in-plot explanation
text(0.1,1.8,'Cone property:','FontSize',8);
text(0.1,1.6,'\alpha z stays on same axis.','FontSize',8);
text(0.1,1.4,'Not convex: segment between','FontSize',8);
text(0.1,1.2,'e_1 and e_2 is missing.','FontSize',8);


%% (d) Convex cone condition: alpha x + beta y in K
% Here we illustrate the key law:
%   K is a convex cone  <=>  for all x,y in K and alpha,beta >= 0,
%                             alpha x + beta y is also in K.
%
% For intuition: think of K as a set of "allowed directions".
% - Cone: if a direction is allowed, any longer multiple is also allowed.
% - Convex: if two directions are allowed, any "mix" of them is allowed.
% Combining both:
%   any nonnegative linear combination alpha x + beta y stays in K.

% We construct a simple convex cone: the same wedge as in (a), but only
% the boundary rays and a point inside.

v1 = [-1; 1];
v2 = [ 1; 1];

nexttile;  % subplot (2,2)
hold on; grid on; axis equal;
xlabel('x_1'); ylabel('x_2');
title('(d) Convex cone: \alpha x + \beta y stays inside');

alphas = linspace(0,2.2,50);
ray1   = alphas .* v1;
ray2   = alphas .* v2;

plot(ray1(1,:), ray1(2,:), 'b', 'LineWidth', 2);
plot(ray2(1,:), ray2(2,:), 'b', 'LineWidth', 2);
plot(0,0,'ko','MarkerFaceColor','k');

% pick two points in the cone
x = 0.8 * v1;
y = 1.2 * v2;

plot(x(1), x(2), 'ro', 'MarkerFaceColor','r');
plot(y(1), y(2), 'ro', 'MarkerFaceColor','r');
text(x(1)-0.4,x(2)+0.1,'x','FontSize',8);
text(y(1)+0.1,y(2)+0.1,'y','FontSize',8);

% nonnegative combination alpha x + beta y
alpha = 0.7;
beta  = 0.4;
z     = alpha * x + beta * y;

plot(z(1), z(2), 'gs', 'MarkerFaceColor','g');
text(z(1)-0.6,z(2)-0.2,'z = \alpha x + \beta y','FontSize',8);

legend('Ray v_1','Ray v_2','Origin','x \in K','y \in K','z \in K','Location','northeast');

% in-plot explanation
text(-2.2,2.2,'Convex cone law:','FontSize',8);
text(-2.2,2.0,'if x,y in K and','FontSize',8);
text(-2.2,1.8,'\alpha,\beta \ge 0 then','FontSize',8);
text(-2.2,1.6,'\alpha x + \beta y in K.','FontSize',8);

